{% set name = "libnpp" %}
{% set version = "13.0.1.2" %}
{% set cuda_version = "13.0" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/{{ name }}/{{ platform }}/{{ name }}-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: b99e7e145283667728e5fd1bf99c79ed9825c164d3c4a40f6dc549cb0b0e1333  # [linux64]
  sha256: 6d06bd527b3cb17e354a3d25f9334ff9f972f6af7dc1fe0a7e0f5b87ba6e618a  # [aarch64]
  sha256: cec65b472cdbd97c557cc45cabc5998288b48c166b9e05d95b8ee3e44083906b  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]
    - patchelf <0.18.0                      # [linux]

outputs:
  - name: libnpp
    files:
      - lib/libnpp*.so.*                            # [linux]
      - targets/{{ target_name }}/lib/libnpp*.so.*  # [linux]
      - Library\bin\npp*.dll      # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
         - cuda-version {{ cuda_version }}
      run:
         - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath.sh
      commands:
        - test -L $PREFIX/lib/libnppc.so.{{ version }}                                          # [linux]
        - test -L $PREFIX/lib/libnppc.so.{{ version.split(".")[0] }}                            # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libnppc.so.{{ version.split(".")[0] }}  # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnppc.so.{{ version }}                # [linux]
        - bash test-rpath.sh                                                                    # [linux]
        - if not exist %LIBRARY_BIN%\nppc64_{{ version.split(".")[0] }}.dll exit 1              # [win]
    about:
      home: https://developer.nvidia.com/npp
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: NPP native runtime libraries
      description: |
        NPP native runtime libraries
      doc_url: https://docs.nvidia.com/cuda/npp/index.html

  - name: libnpp-dev
    build:
      run_exports:
        - {{ pin_subpackage("libnpp", max_pin="x") }}
    files:
      - lib/libnpp*.so                            # [linux]
      - lib/pkgconfig                             # [linux]
      - targets/{{ target_name }}/include         # [linux]
      - targets/{{ target_name }}/lib/libnpp*.so  # [linux]
      - targets/{{ target_name }}/lib/stubs       # [linux]
      - Library\include                           # [win]
      - Library\lib\{{ target_name }}             # [win]
    requirements:
      run:
        - libnpp >={{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("libnpp", exact=True) }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - libnpp-static >={{ version }}      # [linux]
    test:
      commands:
        - test -L $PREFIX/lib/libnppc.so                                  # [linux]
        - test -f $PREFIX/lib/pkgconfig/nppc*.pc                          # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/npp.h         # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnppc.so        # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/stubs/libnppc.so  # [linux]
        - if not exist %LIBRARY_INC%\npp.h exit 1                         # [win]
        - if not exist %LIBRARY_LIB%\{{ target_name }}\nppc.lib exit 1    # [win]
    about:
      home: https://developer.nvidia.com/npp
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: NPP native runtime libraries
      description: |
        NPP native runtime libraries
      doc_url: https://docs.nvidia.com/cuda/npp/index.html

  - name: libnpp-static
    build:
      skip: True  # [not linux]
    requirements:
      run:
        - libnpp-dev >={{ version }}
    files:
      - targets/{{ target_name }}/lib/libnpp*_static.a
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnppc_static.a
    about:
      home: https://developer.nvidia.com/npp
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: NPP native runtime libraries
      description: |
        NPP native runtime libraries
      doc_url: https://docs.nvidia.com/cuda/npp/index.html

about:
  home: https://developer.nvidia.com/npp
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: NPP native runtime libraries
  description: |
    NPP native runtime libraries
  doc_url: https://docs.nvidia.com/cuda/npp/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
  feedstock-name: libnpp
